# .sops.yaml
keys:
  - &age_system age1alh6wlt64qlhzrznj0k6gtp3u8xezvytml2ah4gmceurjvtshstq2h9l8t
  - &age_dylan age1alh6wlt64qlhzrznj0k6gtp3u8xezvytml2ah4gmceurjvtshstq2h9l8t

creation_rules:
  - path_regex: .*
    key_groups:
      - age:
          - *age_system
          - *age_dylan