# .sops.yaml
keys:
  - &age_andromeda age1tj0uulwu6h986aqswhdtffnm0mtsg44e92358ytrg3mele69wqgs0z8tyn
  - &age_quasar age1tlucxz2jugsw6knmlax65qqkre954ystq3mjhya80sy7lzgasddsmsvfn5
  - &age_dylan age1alh6wlt64qlhzrznj0k6gtp3u8xezvytml2ah4gmceurjvtshstq2h9l8t

creation_rules:
  - path_regex: .*
    key_groups:
      - age:
          - *age_andromeda
          - *age_quasar
          - *age_dylan