# .sops.yaml
keys:
  - &age_system age1fxlqh39pvz24g7eh3ztk7wqnmfggmhpgqwesme7guukekd4vhdmqrxzd6p
  - &age_dylan age1hnef9nl6teajffyhangppu5gvue9ku4ss9r0kn8r7vkgkq086f4qajxu0u

creation_rules:
  - path_regex: .*
    key_groups:
      - age:
          - *age_system
          - *age_dylan